sudo: required
dist: trusty
language: python
node_js:
- '4.4'
python:
- '2.7'
addons:
  apt:
    packages:
    - wget
    - npm
before_install:
- openssl aes-256-cbc -K $encrypted_6e3a1461f651_key -iv $encrypted_6e3a1461f651_iv
-in crm/config/client_secret_travis.json.enc -out crm/config/client_secret.json -d
- sudo pip install invoke
- pip install requests
install:
- invoke download
- invoke install
before_script:
- invoke build
script:
- invoke test
deploy:
  provider: gae
  keyfile: crm/config/client_secret.json
  project: iogrowcrm
  skip_cleanup: true
  on: production
