sudo: required
dist: trusty
language: node_js
node_js:
- '4.4'
python:
- '2.7'
addons:
  apt:
    packages:
    - wget
before_install:
- openssl aes-256-cbc -K $encrypted_e45c924b1dd0_key -iv $encrypted_e45c924b1dd0_iv
  -in client_secret.json.travis.enc -out client_secret.json -d
- pip install pyinvoke
install:
- invoke download
- invoke install
before_script:
- invoke build
script:
- invoke test
deploy:
  provider: gae
  keyfile: 'crm/config/client_secret.json'
  project: iogrowcrm
  skip_cleanup: true
