application: gcdc2013-iogrow
version: 4
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail
libraries:
- name: jinja2
  version: latest
- name: endpoints
  version: latest
- name: django
  version: "1.4"

handlers:
- url: /static
  static_dir: static
# Endpoints handler
- url: /_ah/spi/.*
  script: services.application

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
- url: /.*
  script: handlers.app

