application: gcdc2013-iogrow
version: 9
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail
libraries:
- name: jinja2
  version: latest
- name: endpoints
  version: latest
- name: django
  version: "1.4"
- name: ssl
  version: latest

builtins:
- remote_api: on

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /static
  static_dir: static
# Endpoints handler
- url: /_ah/spi/.*
  script: services.application

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
- url: /.*
  script: handlers.app
