application: iogrow-dev
version: 5
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: endpoints
  version: latest

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
    
- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /lib
  static_dir: static/lib

- url: /partials
  static_dir: static/partials

- url: /stylesheets
  static_dir: static/stylesheets
# Endpoints handler
- url: /_ah/spi/.*
  script: services.application
- url: /.*
  script: handlers.app
