application: gcdc2013-iogrow
version: 18
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail
libraries:
- name: jinja2
  version: latest
- name: endpoints
  version: latest
- name: django
  version: "1.4"
- name: ssl
  version: latest

builtins:
- remote_api: on
- appstats: on #/_ah/stats/
includes:
- lib/mapreduce/include.yaml
handlers:
- login: admin
  script: pipeline.handlers._APP
  url: /_ah/pipeline.*
# - login: admin
#   script: mapreduce.main.APP
#   url: /mapreduce(/.*)?
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /static
  static_dir: static

- url: /static/new_web_site/google_drive_files
  static_dir: static/new_web_site/google_drive_files
  expiration: "30d"

# Endpoints handler
- url: /_ah/spi/.*
  script: services.application

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin 
- url: /.*
  script: handlers.app



